image: alpine/latest
packages:
  - coreutils
  - make
  - npm
sources:
  - https://git.sr.ht/~nka/crypto
secrets:
  - 2c93dcdd-ab19-4fe7-86af-a48cfa32cf07
  - ae2cd5c2-6598-4d87-bb2c-69cc8cead737
environment:
  PATH: $HOME/.local/bin:$PATH
tasks:
  - setup: |
      cat ~/.netlify-auth-token >> ~/.buildenv
      cat ~/.netlify-site-id >> ~/.buildenv
      npm config set prefix ~/.local
      cd crypto
      make setup
  - build: |
      cd crypto
      make build
  - deploy: |
      cd crypto
      make deploy
