image: alpine/latest
packages:
  - make
  - npm
sources:
  - https://git.sr.ht/~nka/crypto
secrets:
  - 2c93dcdd-ab19-4fe7-86af-a48cfa32cf07
  - ae2cd5c2-6598-4d87-bb2c-69cc8cead737
tasks:
  - buildenv: |
      cat ~/.netlify-auth-token >> ~/.buildenv
      cat ~/.netlify-site-id >> ~/.buildenv
      echo 'export PATH=$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' >> ~/.buildenv
      npm config set prefix ~/.local
  - setup: |
      cd crypto
      make setup
  - build: |
      cd crypto
      make build
  - deploy: |
      cd crypto
      make deploy
